### ISSUE TITLE
Please update dependencies or be more relax

### ISSUE THREAD

**Issue by JSteunou** [alexbeletsky/backbone-computedfields#27]
npm deps are very strict and old. Would be nice to allow newer underscore, would avoid loading more than one underscore lib when using builder like webpack.

**Comment by alexbeletsky** [comment]
Totally agree, would you please consider to update and shoot a PR?

**Comment by JSteunou** [comment]
I can look at badges, but I never used those so I have to learn about it first :p

**Comment by alexbeletsky** [comment]
Integrated baged and pushed updated version. Thanks a lot for your help :)
