### ISSUE TITLE
Transient fields

### ISSUE THREAD

**Issue by trigoesrodrigo** [alexbeletsky/backbone-computedfields#30]
Hi.
Would it be possible to implement something similar to the transient fields in backbone.mutators?
Usually I need computed fields to be visible in Views but I don't want to be sent to the server. I'm using Marionette and Handlebars and the data passed to Handlebars templates is processed by calling `toJSON` on the model, thus, setting `toJSON:false` in computed preferences excludes the field from the data sent to the server, but also leaves me without the field in the view. Having a `transient:true` preferencie would allow a more flexible behavior.

**Comment by alexbeletsky** [comment]
Can this be helpful,

https://github.com/alexbeletsky/backbone-computedfields#json-payload

?

**Comment by trigoesrodrigo** [comment]
I found that in the docs just minutes after raising the issue :)

Right now I'm overriding `serializeModel` in my Views to pass '`computedFields:true` in the `model.toJSON`calls to have access to the computed fields. 

However that forces to change all views dealing with computed models to override `serializeModel` (either explicitly, subclassing or with mixins -because Marionette Behaviors don't have access to that method, and there aren't other overriding mechanisms-). I find that a little but cumbersome and I think that having the preference in the model would be easier, but I understand that you might not want to change that.

Thanks for the awesome library anyway ;)

**Comment by alexbeletsky** [comment]
You are welcome :)
