### ISSUE TITLE
wrap toJSON replace toJSON by a String

### ISSUE THREAD

**Issue by JSteunou** [alexbeletsky/backbone-computedfields#32]
I have this weird error since I do a new npm install so might be related to a new release of something... (underscore ?) I will investigate more. But for now, all my models using backbone.computedFields are KOs because of toJSON being a string instead of a function

**Comment by JSteunou** [comment]
False alarm, I had _.wrap erase by underscore.string#wrap

**Comment by alexbeletsky** [comment]
Ok, closing it then :)

**Comment by happylinks** [comment]
Also had this issue, if you use "_.mixin(s.exports());" the _.wrap is indeed overwritten. Took me a while to find! Thanks for this post!

**Comment by JSteunou** [comment]
I already send a PR to underscore.string but they did not merge in yet.
