### ISSUE TITLE
Option "silent" does not work

### ISSUE THREAD

**Issue by JSteunou** [alexbeletsky/backbone-computedfields#34]
When initializing a model with some value and options `{silent: true}` events `change` are still triggered from computed fields.

I noticed a couple `skipChangeEvent` inside your code, is this the old name from an old backbone version of `silent`?

**Comment by alexbeletsky** [comment]
Hey @JSteunou, thanks a lot for reporting this. The library has quite good test suite, can you please to run it and reproduce the problem you are talking about?

Not sure, but very likely something has changed in Backbone.. and *likely* not that hard to fix it :)

**Comment by JSteunou** [comment]
Nope, nothing about init or set with options in the test suite.

**Comment by JSteunou** [comment]
Ok I understand better now. `skipChangeEvent` is `backbone.computedFields` internal to avoid infinite loop, nothing to do with `silent` bb option.

Then Model#set options like `{silent: true}` could not be passed along from an initial set to a computed set because computedFields listen to `change` events to know when to compute fields, so silent = no change event = no computed fields update, foolish idea of my, I'm closing it.
